name:
  llm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=24.0
  - pip:
    - langchain==0.1.17
    - pypdf==4.2.0
    - openai==1.26.0
    - pandas==2.2.2
    - numpy==1.26.4
    - streamlit==1.35.0
    - chromadb==0.5.0
    - pdfplumber==0.11.0